### ISSUE TITLE
VSCode 自动关联 Scoop 应用清单

### ISSUE THREAD

**Issue by wordpure** [abgox/ScoopType#1]
大部分 bucket 都沿用了官方 bucket 模板仓库的文件结构，可以在 VSCode 的配置文件加上下面这段，自动关联这类 Scoop 应用程序清单，省去手动添加 `$schema` 的麻烦。

```json
"json.schemas": [
    {
      "fileMatch": [
        "bucket/*.json"
      ],
      "url": "https://abgox.github.io/ScoopType/schema/zh-CN.json"
    }
  ]
```

**Comment by wordpure** [comment]
顺带一提，大佬有兴趣把 schema 发布到 [JSON Schema Store](https://www.schemastore.org/json/)，或者把它和 PSCompletions 一起自荐给 Scoop 官方吗？

好东西应该让更多人知道❤️

**Comment by abgox** [comment]
- 在配置文件中添加自动关联是应该的, 就像我创建的一个 bucket [abgo_bucket](https://github.com/abgox/abgo_bucket) 就是这样做的
- 这个 schema 更多的还是给我自己使用的, 所以暂时没有发布的想法(会让许多事情变得麻烦), 可能后续会迁移到这个仓库吧 [schema](https://github.com/abgox/schema)

**Comment by wordpure** [comment]
> 在配置文件中添加自动关联是应该的, 就像我创建的一个 bucket [abgo_bucket](https://github.com/abgox/abgo_bucket) 就是这样做的

是这样，不过现在 README 里只提到了添加 `$schema` 属性这种方式，可能有些萌新不知道还可以自动关联。把这部分内容也加到 README 里会对他们更友好一些

**Comment by abgox** [comment]
嗯, 后面我会添加
